#-*- coding: utf-8 -*-
[
'TV LCD 19 pol HD',
'TV LCD 22 pol HD ',
'TV LCD 26 pol HD ',
'TV LCD 32 pol HD ',
'TV LCD 42 pol HD ',
'TV LCD 47 pol HD ',
'TV LCD 55 pol HD ',
'TV LCD 19 pol Full HD ',
'TV LCD 22 pol Full HD ',
'TV LCD 26 pol Full HD ',
'TV LCD 32 pol Full HD ',
'TV LCD 42 pol Full HD ',
'TV LCD 47 pol Full HD ',
'TV LCD 55 pol Full HD ',
'TV LED 19 pol Full HD ',
'TV LED 22 pol Full HD ',
'TV LED 26 pol Full HD ',
'TV LED 32 pol Full HD ',
'TV LED 42 pol Full HD ',
'TV LED 47 pol Full HD ',
'TV LED 55 pol Full HD ',
'TV LED 19 pol Full HD 3D',
'TV LED 22 pol Full HD 3D',
'TV LED 26 pol Full HD 3D',
'TV LED 32 pol Full HD 3D',
'TV LED 42 pol Full HD 3D',
'TV LED 47 pol Full HD 3D',
'TV LED 55 pol Full HD 3D',
'DVD player   ',
'DVD player com karaokê  ',
'Blu-ray player   ',
'Blu-ray player compativel 3D  ',
'Home Theater 2.1 até 1000W ',
'Home Theater 5.1 até 1000W ',
'Home Theater 7.1 até 1000W ',
'Home Theater 5.1 acima de 1000W ',
'Home Theater 7.1 acima de 1000W ',
'Home Theater 5.1 acima de 1000W wireless',
'Home Theater 7.1 acima de 1000W wireless',
'Som portátil   ',
'Micro System   ',
'Som dock station   ',
'iPod shuffle 2 GB  ',
'iPod nano 8GB  ',
'iPod nano 16GB  ',
'iPod touch 8GB  ',
'iPod touch 32GB  ',
'iPod touch 64GB  ',
'iPod classic   ',
'iPhone 4 16GB  ',
'iPhone 4 32GB  ',
'iPhone 4S 16GB  ',
'iPhone 4S 32GB  ',
'iPhone 4S 64GB  ',
'iPad 2 16GB Wifi ',
'iPad 2 32GB Wifi ',
'iPad 2 64GB Wifi ',
'iPad 2 16GB 3G ',
'iPad 2 32GB 3G ',
'iPad 2 64GB 3G ',
'Apple TV   ',
'Macbook Air 11 pol 64GB ',
'Macbook Air 11 pol 128GB ',
'Macbook Air 13 pol 128GB ',
'Macbook Air 13 pol 256GB ',
'Macbook Pro 13 pol  ',
'Macbook Pro 15 pol  ',
'Macbook Pro 17 pol  ',
'iMac 21 pol  ',
'iMac 27 pol  ',
'Galaxy tab 10.1 pol 16GB ',
'Galaxy tab 10.1 pol 32GB ',
'Camera digital até 12MP zoom digital ',
'Camera digital até 12MP zoom ótico ',
'Camera digital mais de 12MP zoom digital ',
'Camera digital mais de 12MP zoom ótico ',
'Filmadora digital Flash SD ',
'Filmadora digital HDD SD ',
'Filmadora digital Flash Full HD ',
'Filmadora digital HDD Full HD ',
'MP3 player até 2GB sem rádio ',
'MP3 player mais de 2GB sem rádio ',
'MP3 player até 2GB com rádio ',
'MP3 player mais de 2GB com rádio ',
'GPS 4.3 pol sem câmera de ré ',
'GPS 5 pol sem câmera de ré ',
'GPS 7 pol sem câmera de ré ',
'GPS 4.3 pol com câmera de ré ',
'GPS 5 pol com câmera de ré ',
'GPS 7 pol com câmera de ré ',
'Monitor LCD 15 pol  ',
'Monitor LCD 17 pol  ',
'Monitor LCD 19 pol  Intel i3',
'Monitor LCD 22 pol  Intel i3',
'Notebook 2GB RAM 320GB Intel i3',
'Notebook 4GB RAM 320GB Intel i3',
'Notebook 6GB RAM 320GB Intel i3',
'Notebook 8GB RAM 320GB Intel i3',
'Notebook 2GB RAM 500GB Intel i3',
'Notebook 4GB RAM 500GB Intel i3',
'Notebook 6GB RAM 500GB Intel i3',
'Notebook 8GB RAM 750GB Intel i3',
'Notebook 2GB RAM 750GB Intel i3',
'Notebook 4GB RAM 750GB Intel i3',
'Notebook 6GB RAM 750GB Intel i5',
'Notebook 8GB RAM 750GB Intel i5',
'Notebook 2GB RAM 320GB Intel i5',
'Notebook 4GB RAM 320GB Intel i5',
'Notebook 6GB RAM 320GB Intel i5',
'Notebook 8GB RAM 320GB Intel i5',
'Notebook 2GB RAM 500GB Intel i5',
'Notebook 4GB RAM 500GB Intel i5',
'Notebook 6GB RAM 500GB Intel i5',
'Notebook 8GB RAM 750GB Intel i5',
'Notebook 2GB RAM 750GB Intel i5',
'Notebook 4GB RAM 750GB Intel i5',
'Notebook 6GB RAM 750GB Intel i7',
'Notebook 8GB RAM 750GB Intel i7',
'Notebook 2GB RAM 320GB Intel i7',
'Notebook 4GB RAM 320GB Intel i7',
'Notebook 6GB RAM 320GB Intel i7',
'Notebook 8GB RAM 320GB Intel i7',
'Notebook 2GB RAM 500GB Intel i7',
'Notebook 4GB RAM 500GB Intel i7',
'Notebook 6GB RAM 500GB Intel i7',
'Notebook 8GB RAM 750GB Intel i7',
'Notebook 2GB RAM 750GB Intel i7',
'Notebook 4GB RAM 750GB Intel i7',
'Notebook 6GB RAM 750GB Wifi',
'Notebook 8GB RAM 750GB Wifi',
'Impressora jato de tinta  Wifi',
'Impressora jato de tinta multifuncional Wifi',
'Impressora laser  ',
'Impressora laser multifuncional ',
'Impressora jato de tinta  ',
'Impressora jato de tinta multifuncional ',
'Impressora laser  ',
'Impressora laser multifuncional ',
'Nintendo Wii   ',
'PS3 160GB  ',
'PS3 320GB  ',
'Xbox 360 250GB  ',
'Xbox 360 320GB  ',
'Nintendo DS   ',
'Nintendo Dsi   ',
'Nintendo 3DS   ',
'Geladeira 1 porta até 400L ',
'Geladeira 2 portas até 400L ',
'Geladeira 2 portas mais de 400L ',
'Freezer vertical até 250L  ',
'Freezer vertical com mais de 250L  ',
'Microondas até 30L  ',
'Microondas mais de 30L  ',
'Lavadora de roupa 8,5kg/9kg  ',
'Lavadora de roupa 11kg  ',
'Lava e seca roupas 8,5kg/9kg  ',
'Lava e seca roupas 11kg  ',
'Secadora de roupa 10kg  ',
'Secadora de roupa 17kg  ',
'Fogão 4 bocas embutido ',
'Fogão 4 bocas embutido ',
'Fogão 4 bocas de piso ',
'Fogão 4 bocas de piso ',
'Fogão 5 bocas embutido ',
'Fogão 5 bocas embutido ',
'Fogão 5 bocas de piso ',
'Fogão 5 bocas de piso ',
'Lava louças 6 serviços  ',
'Lava louças 12 serviços  ',
'Ar condicionado split 9.000 BTUs  ',
'Ar condicionado split 12.000 BTUs  ',
'Ar condicionado split 18.000 BTUs  ',
'Adega 8 garrafas  ',
'Adega 12 garrafas  ',
'Adega 18 garrafas  ',
'Adega 28 garrafas  ',
'Aspirador de pó   ',
'Aspirador de pó portátil  ',
'Secador de cabelo   ',
'Chapinha de cabelo   ',
'Maquina Nespresso   ',
'Maquina de espresso automática  ',
'Maquina de espresso Dolce Gusto   ',
'Ferro a vapor  '
].each do |prod_name|
  Product.create(:name => prod_name.strip)
end
